# Generated by Django 3.2.10 on 2021-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='live_date',
            field=models.DateTimeField(null=True),
        ),
    ]
